### ISSUE TITLE
Issue with plot()

### ISSUE THREAD

**Issue by jswlr** [google/CausalImpact#16] opened 2018-04-05 21:14 UTC
Is df one of the inputs to plot function? I keep having issue with plot function:

plot(impact)
Error in plot(impact) : argument "df" is missing, with no default

**Comment by alhauser** [comment] 2018-04-06 05:36
`plot.CausalImpact()` doesn't have an argument `df`, so it must be an error thrown by a function called internally.

Could you provide a minimal example that produces the error message?

**Comment by jswlr** [comment] 2018-04-06 16:35
Thanks for the reply! I just played with the basic function.

**>pre.period <- c(as.POSIXct(start_time_baseline,format="%Y-%m-%d %H:%M:%S"),as.POSIXct(end_time_baseline,format="%Y-%m-%d %H:%M:%S"))**

**>post.period <- c(as.POSIXct(start_time_test,format="%Y-%m-%d %H:%M:%S"),as.POSIXct(end_time_test,format="%Y-%m-%d %H:%M:%S"))**

**>times <- seq(as.POSIXct(start_time_baseline,format="%Y-%m-%d %H:%M:%S"), as.POSIXct(end_time_test,format="%Y-%m-%d %H:%M:%S"), by = "min")**

**>data_input <- zoo(data,times)**

**>impact <- CausalImpact(data_input, pre.period, post.period)**

**> head(data_input)**
                    concurrency   effquery
2018-02-06 06:00:00    1.044511 0.01392750
2018-02-06 06:01:00    1.012158 0.01334233
2018-02-06 06:02:00    1.030761 0.01370150
2018-02-06 06:03:00    1.028775 0.01425533
2018-02-06 06:04:00    1.060800 0.01427050
2018-02-06 06:05:00    1.008172 0.01356117


**> impact**
Posterior inference {CausalImpact}

Average        Cumulative       
Actual                   3              8644             
Prediction (s.d.)        3.2 (0.64)     9257.5 (1840.40) 
95% CI                   [2, 4.4]       [5652, 12729.7]  
                                                         
Absolute effect (s.d.)   -0.21 (0.64)   -613.83 (1840.40)
95% CI                   [-1.4, 1]      [-4086.0, 2991]  
                                                         
Relative effect (s.d.)   -6.6% (20%)    -6.6% (20%)      
95% CI                   [-44%, 32%]    [-44%, 32%]      

Posterior tail-area probability p:   0.36713
Posterior prob. of a causal effect:  63%


**> plot(impact)**
Error in plot(impact) : argument "df" is missing, with no default

**Comment by alhauser** [comment] 2018-04-09 07:56
Thanks for the snippet; I don't see an obvious problem in these lines, and I can't reproduce the problem.

Could you extend the example to be self-consistent, i.e. provide all data needed to reproduce it (`data` e.g. as CSV, `start_time_baseline`, `end_time_baseline`, `start_time_test`, `end_time_test`)?

**Comment by jswlr** [comment] 2018-04-12 04:08
[data.txt](https://github.com/google/CausalImpact/files/1901288/data.txt)
Absolutely! .csv isn't supported for attachment. I am attaching a .txt file.

**Comment by alhauser** [comment] 2018-04-20 08:39
Thanks!

I tried to reproduce the problem with the following code:

```r
library(CausalImpact)

data <- read.table("data.txt", header = TRUE, sep = " ")

start_time_baseline <- "2018-02-06 06:00:00"
end_time_baseline <- "2018-02-09 06:00:00"
start_time_test <- "2018-02-09 07:00:00"
end_time_test <- "2018-02-11 01:54:00"

pre.period <- c(as.POSIXct(start_time_baseline,format="%Y-%m-%d %H:%M:%S"),
                as.POSIXct(end_time_baseline,format="%Y-%m-%d %H:%M:%S"))
post.period <- c(as.POSIXct(start_time_test,format="%Y-%m-%d %H:%M:%S"),
                 as.POSIXct(end_time_test,format="%Y-%m-%d %H:%M:%S"))
times <- seq(as.POSIXct(start_time_baseline,format="%Y-%m-%d %H:%M:%S"),
             as.POSIXct(end_time_test,format="%Y-%m-%d %H:%M:%S"), by = "min")
data_input <- zoo(data,times)
impact <- CausalImpact(data_input, pre.period, post.period)

head(data_input)
impact
plot(impact)
```

I don't get the error you describe, the plot looks fine... I'm just guessing the times that are missing in your code snippet though; feel free to give me the right values that you actually use in your example.

(BTW: the plot shows your data has a strong daily pattern; you might want to specify this seasonality, e.g. by adding an "hour of the day" effect: `CausalImpact(..., model.args = list(nseasons = 24, season.duration = 60))`)

**Comment by alhauser** [comment] 2021-07-15 16:51
Closing as I couldn't reproduce the problem.

**Closed by alhauser** 2021-07-15 16:51 UTC
