### ISSUE TITLE
error installing package

### ISSUE THREAD

**Issue by merveakbas** [google/CausalImpact#22] opened 2018-05-31 14:28 UTC
Hello hello, 
I upgraded my base R to the latest version yesterday. I also re-installed the causal impact package with a bunch of other packages. 

Now, when I run
```library(CausalImpact)```

I get the following error:

Warning: S3 methods ‘ToString.default’, ‘ToString.table’ were declared in NAMESPACE but not found
Error : object ‘GammaPrior’ is not exported by 'namespace:Boom'

Does anyone have a suggested solution for this? Thanks much in advance...

**Comment by merveakbas** [comment] 2018-05-31 20:11
>I tried

```install.packages(Boom)
library(Boom) 
library(CausalImpact)```

still getting the same error...

**Comment by steve-the-bayesian** [comment] 2018-05-31 20:22
update.packages("Boom")

Restart R.

library(CausalImpact)

**Comment by merveakbas** [comment] 2018-05-31 20:27
Just tried that  - still getting the same error (???)
I have the latest version of Rstudio as well - just double checked that.

**Comment by merveakbas** [comment] 2018-05-31 20:29
I double checked that I have the latest version of Boom as well - it is 0.8

**Comment by steve-the-bayesian** [comment] 2018-05-31 20:38
Does the same thing happen when you

library(bsts)

bsts is a dependency of CausalImpact, and Boom is a dependency of bsts.  If
you can load and use bsts then CausalImpact needs updating.  If you can't
then either bsts or Boom needs updating.
The latest bsts is 0.8.0.

Are you Windows, Mac, or Linux?

**Comment by merveakbas** [comment] 2018-05-31 21:05
This is interesting - I reinstalled bsts but when i check the version, it says 0.7.1
I am on a Mac

**Comment by merveakbas** [comment] 2018-05-31 21:09
I think my problem lies in here

There are binary versions available but the source versions are later:
              binary source needs_compilation
BoomSpikeSlab  0.9.0  1.0.0              TRUE
bsts           0.7.1  0.8.0              TRUE

I answer yes but it somehow doesnt work

**Comment by steve-the-bayesian** [comment] 2018-05-31 22:59
Interesting.  The Boom results page on CRAN shows an error for OSX, so I
wonder if the OSX version didn't get built.
I have asked on r-package-devel.

**Comment by merveakbas** [comment] 2018-05-31 23:52
Thanks much for checking !

**Comment by merveakbas** [comment] 2018-06-01 14:58
For now, I reinstalled R.3.3 and am using those libraries... I look forward to getting news on this though since I know now that the problem is that I can't update my BoomSpikeSlab package

**Comment by steve-the-bayesian** [comment] 2018-06-01 15:19
For testing purposes, how do you know the culprit is BoomSpikeSlab vs Boom
or bsts?

**Comment by merveakbas** [comment] 2018-06-05 14:10
Sorry for late reply: Boom upgrades to latest version successfully, but after that BoomSpikeSlab does not upgrade, it fails. And i believe after that, both btst and Causal Impact failed to upgrade..

**Comment by steve-the-bayesian** [comment] 2018-06-06 16:39
Working hypothesis is that the Boom build for OSX is timing out on CRAN, so
they actually don't have the latest version, and that impedes downstream
dependencies BoomSpikeSlab and bsts.

I'm in touch with Simon Urbanek (OSX maintainer for cran) about the issue.

**Comment by steve-the-bayesian** [comment] 2018-06-07 21:15
The latest versions of Boom, BoomSpikeSlab, and bsts for OSX are now on
CRAN .  No explanation yet for the previous failure (maybe a build timeout).

@merveakbas, can you see if this solves the issue you were having with
CausalImpact?

**Comment by merveakbas** [comment] 2018-06-11 13:01
Ah - thanks much for the update!!! - yeah let me check out and I will report.

**Comment by timandrews335** [comment] 2018-09-11 02:10
I'm getting the same error with Ptr.hpp, but on Ubuntu 18.04 and a first installation of CausalImpact.  I see the issue both on R 3.4 (in the bionic repo) and after adding the official R repo and upgrading to 3.5.

On Windows 10 and R 3.4, CausalImpact installed fine.

**Comment by steve-the-bayesian** [comment] 2018-09-13 21:20
The CRAN maintainers don't have the latest version of BOOM published for linux on x64.  The workaround is to download the package source and 
MAKEFLAGS="-j 24" R CMD INSTALL Boom_0.8.tar.gz

**Comment by acorso522md** [comment] 2018-10-26 20:16
Where do I get the relevant package source for linux? Your naming convention here lines up with the R version on CRAN but I can't reuse that one it would seem.

**Comment by xbeta** [comment] 2019-01-04 01:21
I am not sure who owns BoomSpikeSlab. The Github repo is a mirror.

But I face similar problem when installing on my macOS

```

Error: package or namespace load failed for ‘BoomSpikeSlab’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/r_libs/BoomSpikeSlab/libs/BoomSpikeSlab.so':
  dlopen(/r_libs/BoomSpikeSlab/libs/BoomSpikeSlab.so, 6): Symbol not found: __ZN4BOOM9GlobalRng3rngE
  Referenced from: /r_libs/BoomSpikeSlab/libs/BoomSpikeSlab.so
  Expected in: flat namespace
 in /r_libs/BoomSpikeSlab/libs/BoomSpikeSlab.so
```

**Comment by xbeta** [comment] 2019-01-12 01:50
@steve-the-bayesian 

Thanks for helping, but I still face a few issues similar to this thread about missing header files.

**Comment by xbeta** [comment] 2019-01-12 02:40
@steve-the-bayesian After I run `brew uninstall binutils`, everything seems to work again :-)

**Comment by steve-the-bayesian** [comment] 2019-01-12 14:32
Yay!  I'll disregard your other message about Ptr.  That was because you
had problems building Boom. Sorry you had all the trouble, but I'm happy
you got it working.

**Comment by juliamnh** [comment] 2019-02-04 15:19
Hi @steve-the-bayesian,

I also have the issue that CausalImpact won't install Unfortunately the "brew uninstall binutils" doesn't work for me. I get "Error: No such keg:/usr/local/Cellar/binutils" 

Do you know how I should go about resolving this issue?

Thanks!

Screenshot 1: trying to install CausalImpact
Screenshot 2: trying to install BoomSpikeLab separately

Note that the package Boom is loaded in my library, but then still these packages won't install.

Screenshot 1:
![image 1](https://user-images.githubusercontent.com/47326774/52217133-1bea7100-2898-11e9-9d84-db463d2498c5.png)

Screenshot 2:
![image 2](https://user-images.githubusercontent.com/47326774/52217250-5c49ef00-2898-11e9-87a0-07955d889025.png)

**Comment by steve-the-bayesian** [comment] 2019-02-04 16:25
The compiler errors you're seeing have to do with the BoomSpikeSlab package
not being able to find the C++ code distributed with the Boom package.  If
you have Boom installed through CRAN (e.g. install.packages("Boom"), called
from R).  Then you should not be getting this error.

By any chance did you install the Boom C++ code as a standalone C++
library?  If so then dependencies from CRAN probably won't be able to find
it.

What platform are you running on?  What is the output of the command:
 /usr/lib/bin/Rscript -e "cat(system.file(package='Boom'))"    If you check
the compiler command this is where the compiler is looking for Boom header
files.

**Comment by juliamnh** [comment] 2019-02-05 10:20
Thank you Steve! I don't think I installed it as a standalone. Yesterday, restarting the Rsession didn't help, for some reason, a couple more attempts today did the trick. No idea why, but it seems to work now! I'm gonna remember your suggestions if I run into this again (or my coworkers..). Cheers!

**Comment by keniatw** [comment] 2019-05-21 14:44
Coming very late in the discussion, but I am facing the same errors. I successfully installed Boom, but bsts seems to fail every time, so CausalImpact doesn't install. Get the same messages as juliamnh above. Any suggestions so far? Running R and RStudion on Linux Ubuntu 18.04... Ugh!

**Comment by steve-the-bayesian** [comment] 2019-05-21 14:48
Boom and bsts are in the middle of a major update.  It would have been
better to update them simultaneously, but that's not how things work over
at Cran.  Give it a few days.

**Comment by keniatw** [comment] 2019-05-21 15:15
Thank you, steve-the-bayesian!
I have a workshop soon and folks are supposed to install CausalImpact for it (I am a participant, not the instructor), so I will keep my fingers crossed and check from time to time.  :)

**Comment by steve-the-bayesian** [comment] 2019-05-21 15:31
Boom and BoomSpikeSlab have made it through the process.  I'm happy to
provide the .tgz for the bsts update if you need to install manually.
Hopefully it won't come to that.

**Comment by keniatw** [comment] 2019-05-21 16:20
Yay! I'd love to have it. I tried with the 0.8.0 tar.gz but didn't work either. Do you have an updated version I could try?

**Comment by steve-the-bayesian** [comment] 2019-05-21 16:32
I'll need your actual email address to send the files.  Mine is available
from the boom and bsts packages.

**Comment by keniatw** [comment] 2019-05-21 16:37
Hi Steve!

Kenia here. I'd appreciate any help with the bsts (and CausalImpact for
that matter).

Not 100% sure what the underlying problem may be. I get a notification
saying "/usr/lib/R/etc/Makeconf:174: recipe for target
'aggregate_time_series.o' failed" when trying to install the bsts. Maybe a
problem with the gcc compiler instead? I will try with the tar.gz you'll
send to me and go from there. I will keep you posted!

Thanks very much. It's very kind of you.

Cheers,
Kenia
keniatw@gmail.com

--
[image: Inspire! Sustainable Development Goals]
<https://www.un.org/sustainabledevelopment/blog/2019/05/nature-decline-unprecedented-report/?fbclid=IwAR2NWYrgRci3fKvxQWx18YvqMZqCqgWwVtOV0gW4Ug2DCMKOUF91fYq0-C4>
  KENIA WIEDEMANN
  Physicist & Environmental Scientist
  (857) 919-0284

**Comment by steve-the-bayesian** [comment] 2019-05-21 22:34
FYI bsts version 0.9 was just accepted by CRAN, so it should appear for all
platforms within the next 24-48 hours.

Dynamic regression is fixed in this version, several new state models have
been added, and plotting has been improved.
The update to BOOM was needed so I could support multivariate time series,
which has been by far the most common feature request.  I've got that
more-or-less working in the dev version, which I hope to release to the
world in a month or so (after a bit more debugging and testing).

Sorry for the interruption.

**Comment by abelborges** [comment] 2019-06-06 20:33
Hi, guys. With the current state of affairs, I was able to install `Boom` from CRAN but I'm still having trouble with `bsts`. The error message is similar to @keniatw's:
```
make: *** [/usr/lib64/R/etc/Makeconf:170: create_shared_state_model.o] Error 1
ERROR: compilation failed for package ‘bsts’
```
I'm running Fedora 30. Any ideas?

**Comment by steve-the-bayesian** [comment] 2019-06-06 20:42
Abel,
There is a Boom/bsts update cycle going on right now.  Sorry there is a new
one so soon, but there was a pretty serious bug in v 0.9 that needed
immediate fixing.
Email me and I'll reply with the right set of packages.
Steve

**Comment by abelborges** [comment] 2019-06-06 20:57
Thank you, Steve!

**Comment by yxk4525** [comment] 2019-06-06 23:42
Hi @steve-the-bayesian : I'm also facing the same issue 

make: *** [/usr/lib64/R/etc/Makeconf:170: create_shared_state_model.o] Error 1
ERROR: compilation failed for package ‘bsts’

Can you e-mail me the right set of packages?

Thanks,
Yash
yashkarwa.ms@gmail.com

**Comment by steve-the-bayesian** [comment] 2019-06-06 23:52
Hi Yash,
You (or anyone else who needs them) can get them here:
https://drive.google.com/drive/folders/1cb_oYvYzxJvnnXgSeQhrnkpwV-XVF-nC?usp=sharing

Sorry for the inconvenience.  It should work itself out in a day or two.

Steve

**Comment by abelborges** [comment] 2019-06-07 13:47
@steve-the-bayesian It worked like a charm. Thank you once again

**Comment by DeFilippis** [comment] 2020-04-07 14:02
Hey guys, I'm on Mac OS, and I'm getting the error:

```**logit_spike_slab_wrapper.cc:7:10: fatal error: 'cpputil/Ptr.hpp' file not found
#include "cpputil/Ptr.hpp"
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [logit_spike_slab_wrapper.o] Error 1
ERROR: compilation failed for package ‘BoomSpikeSlab’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/BoomSpikeSlab’**```

Did we ever figure out the solution?

**Comment by DeFilippis** [comment] 2020-04-07 14:16
It works now if I install the packages from source from Steve's Google Drive, but surely that isn't how everybody has to resolve the issue?  For future people installing from source, here's the code:

```
install.packages("Boom_0.9.4.tar.gz", repos = NULL, type="source")
install.packages("BoomSpikeSlab_1.2.2.tar.gz", repos = NULL, type="source")
install.packages("bsts_0.9.3.tar.gz", repos = NULL, type="source")
```

It appears you need to install the packages in that order due to dependencies.

**Comment by DavideMagno** [comment] 2020-04-17 18:42
Hi, I have tried to install Boom 0.9.5 both on a mac locally and on an Ubuntu 18.04 server as a pre-requisite for CasualImpact.

The Mac installation through CRAN was super smooth and took 5 seconds. On Ubuntu, I managed to install version 0.8 but I get errors for any 0.9.x version.

I report below the latest codes before breaking:
`../inst/include/Eigen/src/Core/DenseCoeffsBase.h:650:34: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(2) double}’ [-Wignored-attributes]
   return internal::first_aligned<int(unpacket_traits<DefaultPacketType>::alignment),Derived>(m);
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: compilation failed for package ‘Boom’`

I have the latest g++ (v 7.5) hence nothing to be done on that side?
Thank you in advance

**Comment by steve-the-bayesian** [comment] 2020-04-17 20:17
Davide,
The warning you reported would not cause a compilation failure.  My guess
is that the compilation error is a few lines up.  Can you send more
output?  The reason this can happen is that the Boom build occurs in
parallel, so you got this warning as another branch was failing.  Eigen
generates a ton of warnings, so I'm not surprised by this one.
Steve

FYI, I'm in the middle of a month-long struggle with CRAN to get bsts
updated.  Apologies for the instability while that happens.

Steve

**Comment by DavideMagno** [comment] 2020-04-18 17:42
Hi Steve, after running the installation in the terminal, I found the following errors:

`virtual memory exhausted: Cannot allocate memory
cc1plus: out of memory allocating 488 bytes after a total of 4653056 bytes
/usr/lib/R/etc/Makeconf:176: recipe for target 'LinAlg/VectorView.o' failed
make: *** [LinAlg/VectorView.o] Error 1
make: *** Waiting for unfinished jobs....`

Then 

`/usr/lib/R/etc/Makeconf:176: recipe for target 'Models/Glm/PosteriorSamplers/fill_poisson_mixture_approximation_table_3.o' failed
make: *** [Models/Glm/PosteriorSamplers/fill_poisson_mixture_approximation_table_3.o] Error 1`

And finally

`/usr/lib/R/etc/Makeconf:176: recipe for target 'Models/Glm/PosteriorSamplers/fill_poisson_mixture_approximation_table_2.o' failed
make: *** [Models/Glm/PosteriorSamplers/fill_poisson_mixture_approximation_table_2.o] Error 1`

I checked the RAM availability and seems like I have 3.3GB, is that not enough?

>                       total        used        free      shared  buff/cache   available
>         Mem:           3.9G        320M        3.4G        628K        173M        3.3G
>        Swap:            0B          0B          0B

**Comment by steve-the-bayesian** [comment] 2020-04-19 00:38
Hi Davide,
I'm not a compiler expert, but my guess is that your compiler has set aside
a certain amount of memory for the "stack" (where automatic variables go,
like double, or int).  The file that appears to be the issue sets up a very
large table, and it may be too large for your stack.  Quick work arounds
might include (1) look for a compiler flag that will allow you to control
the stack size, (2) switch to a different compiler (e.g. from gcc to
clang).  You have ample physical memory on your machine for the build.

I ran into the stack size limitation at Google, which is the reason the
table-filling code is split into three parts.  Yours is the first case
outside of Google where I have seen it be a problem.

Searching for stack-related flags in man gcc yields the following promising
candidates:

       -fstack-limit-register=reg
       -fstack-limit-symbol=sym
       -fno-stack-limit
           Generate code to ensure that the stack does not grow beyond a
certain value, either the value of a register or the address of a symbol.
If a larger stack is required, a
           signal is raised at run time.  For most targets, the signal is
raised before the stack overruns the boundary, so it is possible to catch
the signal without taking
           special precautions.

           For instance, if the stack starts at absolute address 0x80000000
and grows downwards, you can use the flags
-fstack-limit-symbol=__stack_limit and
           -Wl,--defsym,__stack_limit=0x7ffe0000 to enforce a stack limit
of 128KB.  Note that this may only work with the GNU linker.

           You can locally override stack limit checking by using the
"no_stack_limit" function attribute.


Steve

**Comment by alhauser** [comment] 2021-07-15 16:56
Assuming this is resolved with current bsts versions.

**Closed by alhauser** 2021-07-15 16:56 UTC
